[package]
name = "nicacher"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"

anyhow = "1.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }

env_logger = "0.10"
tracing = "0.1"
tracing-actix-web = "0.6"
